name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  shell: 'sh -x'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # report all go versions separately
      matrix:
        go-version:
        - "1.16"
        - "1.17"
        - "1.18"
        - "1.19"
        - "1.20"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{matrix.go-version}}

    - name: Build
      run: make test

